__use_yte__: true
executor: slurm
default-resources:
  - mem_mb=4000
  - runtime=60
  - slurm_account="def-nessrobe_cpu"
latency-wait: 60
jobs: 250
retries: 1
local-cores: 1
singularity-args: "--bind /home"
# max-jobs-per-second: 1
max-status-checks-per-second: 2
scheduler: greedy
